// Project data loader
// In development: uses mock data
// In pipeline: loads from projects.json generated by scripts/merge.py
import pipelineProjects from "./projects.json" with { type: "json" };

export interface Project {
  id: string;
  slug: string;
  name: string;
  nameZh?: string;
  blurb: string;
  state: string;
  platform: "kickstarter" | "indiegogo";
  category: string;
  parent_category: string;
  topnice_category: string;
  image_full: string;
  image_med: string;
  image_thumb: string;
  goal: number;
  pledged: number;
  backers_count: number;
  percent_funded: number;
  launched_at: string;
  deadline: string;
  creator_name: string;
  creator_avatar_medium: string;
  location: string;
  country: string;
  staff_pick: boolean;
  video_url: string;
  url: string;
  score: number;
  daysLeft: number;
  story_markdown?: string;
  story_images?: string[];
  ai_intro?: string;
  ai_intro_en?: string;
  ai_highlights?: string[];
  ai_highlights_en?: string[];
  ai_specs?: string[][];
  ai_specs_en?: string[][];
  ai_tiers?: AiTier[];
  ai_risks?: string;
  ai_risks_en?: string;
  ai_risks_structured?: string[][];
  ai_creator_bio?: string;
  ai_creator_bio_en?: string;
  raw_html_hash?: string;
  raw_fetched_at?: string;
  history?: {date: string; backers: number; pledged: number}[];
  ai_gallery?: string[];
  ai_seo_keywords?: string;
}

function computeDaysLeft(deadline: string): number {
  if (!deadline) return 0;
  // Force UTC parsing: most deadlines in the data are stored WITHOUT a trailing
  // 'Z', so `new Date(str)` would interpret them in the local timezone. On a GMT+8
  // build/browser that shifts them 8h early and wrongly flips "live" to "ended".
  const d = new Date(deadline.endsWith('Z') ? deadline : deadline + 'Z');
  const now = new Date();
  return Math.max(0, Math.ceil((d.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)));
}

// Load real pipeline data
const rawProjects: any[] = pipelineProjects?.projects ?? [];

export const allProjects: Project[] = rawProjects.map((p: any) => {
  const daysLeft = computeDaysLeft(p.deadline);
  // IMPORTANT: state must be derived from deadline, never trusted from the JSON snapshot.
  // Campaigns cross their deadline daily, so a stored "live" can already be "ended".
  const state = p.deadline
    ? daysLeft > 0
      ? "live"
      : "ended"
    : p.state || "live";
  return {
    ...p,
    slug: p.slug || p.id,
    daysLeft,
    state,
  };
});

// Derived stats — single source of truth, computed at build time from allProjects.
// Every value is derived from the array itself, so counts can never drift out of sync
// with the data (this replaces the old static "stats" snapshot in projects.json that
// went stale whenever projects were added/removed outside of the pipeline).
export const stats = {
  total: allProjects.length,
  liveNow: allProjects.filter((p) => p.state === "live").length,
  totalRaised: allProjects.reduce((s, p) => s + (p.pledged || 0), 0),
  totalBackers: allProjects.reduce((s, p) => s + (p.backers_count || 0), 0),
};

export function getProjectBySlug(slug: string): Project | undefined {
  return allProjects.find((p) => p.slug === slug);
}

export function getProjectsByCategory(cat: string): Project[] {
  return allProjects.filter((p) => p.topnice_category === cat);
}

console.log(
  `[projects] Loaded ${allProjects.length} projects | state derived from deadline: ` +
    JSON.stringify(
      allProjects.reduce(
        (acc: Record<string, number>, p) => {
          acc[p.state] = (acc[p.state] || 0) + 1;
          return acc;
        },
        {} as Record<string, number>
      )
    )
);
